### PR TITLE
Enproxy intf cleanup

### PR DESCRIPTION
**Pull request by oxtoacart**
While prepping my presentation for Thursday, I realized that the API for opening an enproxy.Conn isn't very standard.  I've updated it to look more like a normal net.Conn, namely using a Dial function.

### CODE REVIEW

**Comment by aranhoide** [comment]
IIRC it's a known issue that this would happen sometimes, but upon QAing this PR I get this every single time I try and test it:

```
aranhoide@duna:~/src/flashlight-build/src/github.com/getlantern/fronted$ go test 
fronted: Creating new PK at: 
fronted: Creating new server cert at: 
fronted: Creating new server cert at: testcert.pem
fronted: About to start server (https) proxy at localhost:0
fronted: Not accepting connections to non-global address: 127.0.0.1:60565
enproxy: Responding Bad Gateway: Unable to get connOut: Unable to dial out to 127.0.0.1:60565: Not accepting connections to non-global address: 127.0.0.1:60565
enproxy: Dest: 127.0.0.1:60565    ProxyHost:     Unable to issue write request: Bad response status for read: 502 Bad Gateway
```

And the test freezes there.  The unit tests for enproxy proper do pass, though.

**Comment by aranhoide** [comment]
Other than the caveat while QAing (which I don't suppose is really caused by any change here) LGTM.

**Comment by oxtoacart** [comment]
> And the test freezes there. The unit tests for enproxy proper do pass, though.

Out of curiosity, if you run the same test in the peerscanner branch (new branch I'm working on), do you get the same issue?

**Comment by aranhoide** [comment]
In the peerscanner branch I get a different issue:

```
--- FAIL: TestNonGlobalAddressNoPort (0.34s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x467bb5]

goroutine 32 [running]:
testing.func·006()
    /usr/local/go/src/testing/testing.go:441 +0x181
github.com/getlantern/fronted.doTestNonGlobalAddress(0xc2080eba70, 0x786c10, 0x9)
    /home/aranhoide/src/flashlight-build/src/github.com/getlantern/fronted/fronted_test.go:118 +0x825
github.com/getlantern/fronted.TestNonGlobalAddressNoPort(0xc2080eba70)
    /home/aranhoide/src/flashlight-build/src/github.com/getlantern/fronted/fronted_test.go:88 +0x3b
testing.tRunner(0xc2080eba70, 0x9106e8)
    /usr/local/go/src/testing/testing.go:447 +0xbf
created by testing.RunTests
    /usr/local/go/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
testing.RunTests(0x80ba18, 0x910640, 0xd, 0xd, 0x7ffffffe6f98b101)
    /usr/local/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc20802a6e0, 0x91b2e0)
    /usr/local/go/src/testing/testing.go:485 +0x6c
main.main()
    github.com/getlantern/fronted/_test/_testmain.go:76 +0x1d5

goroutine 33 [runnable]:
github.com/getlantern/fronted.func·012()
    /home/aranhoide/src/flashlight-build/src/github.com/getlantern/fronted/fronted_test.go:282
created by github.com/getlantern/fronted.startServer
    /home/aranhoide/src/flashlight-build/src/github.com/getlantern/fronted/fronted_test.go:287 +0x3f9

goroutine 18 [IO wait]:
net.(*pollDesc).Wait(0xc20806e680, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20806e680, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20806e620, 0x0, 0x7fb7f2f23a88, 0xc20800b848)
    /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20802c020, 0xc207fff477, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20802c020, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
crypto/tls.(*listener).Accept(0xc20809c4a0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/tls.go:46 +0x6b
github.com/getlantern/idletiming.(*idleTimingListener).Accept(0xc20809c4c0, 0x0, 0x0, 0x0, 0x0)
    /home/aranhoide/src/flashlight-build/src/github.com/getlantern/idletiming/idletiming_listener.go:34 +0xb1
net/http.(*Server).Serve(0xc208050540, 0x7fb7f2f27ca0, 0xc20809c4c0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1728 +0x92
github.com/getlantern/fronted.(*Server).Serve(0xc208010c40, 0x7fb7f2f27ca0, 0xc20809c4c0, 0x0, 0x0)
    /home/aranhoide/src/flashlight-build/src/github.com/getlantern/fronted/server.go:152 +0x33c
github.com/getlantern/fronted.func·012()
    /home/aranhoide/src/flashlight-build/src/github.com/getlantern/fronted/fronted_test.go:283 +0x51
created by github.com/getlantern/fronted.startServer
    /home/aranhoide/src/flashlight-build/src/github.com/getlantern/fronted/fronted_test.go:287 +0x3f9

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 19 [IO wait]:
net.(*pollDesc).Wait(0xc20806e6f0, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20806e6f0, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20806e690, 0x0, 0x7fb7f2f23a88, 0xc20800b6a8)
    /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20802c0d0, 0x486839, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20802c0d0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/getlantern/fronted.func·009()
    /home/aranhoide/src/flashlight-build/src/github.com/getlantern/fronted/fronted_test.go:107 +0x4b
created by github.com/getlantern/fronted.doTestNonGlobalAddress
    /home/aranhoide/src/flashlight-build/src/github.com/getlantern/fronted/fronted_test.go:111 +0x32d

goroutine 26 [select]:
github.com/getlantern/idletiming.func·001()
    /home/aranhoide/src/flashlight-build/src/github.com/getlantern/idletiming/idletiming_conn.go:43 +0x212
created by github.com/getlantern/idletiming.Conn
    /home/aranhoide/src/flashlight-build/src/github.com/getlantern/idletiming/idletiming_conn.go:56 +0x303

goroutine 24 [select]:
github.com/getlantern/idletiming.func·001()
    /home/aranhoide/src/flashlight-build/src/github.com/getlantern/idletiming/idletiming_conn.go:43 +0x212
created by github.com/getlantern/idletiming.Conn
    /home/aranhoide/src/flashlight-build/src/github.com/getlantern/idletiming/idletiming_conn.go:56 +0x303

goroutine 25 [IO wait]:
net.(*pollDesc).Wait(0xc20806e920, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20806e920, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20806e8c0, 0xc208058c00, 0x400, 0x400, 0x0, 0x7fb7f2f23a88, 0xc20800b730)
    /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802c118, 0xc208058c00, 0x400, 0x400, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc208079a40, 0x7fb7f2f27d00, 0xc20802c118, 0x5, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc2080c42c0, 0x17, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc2080c42c0, 0xc2080aa000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:904 +0x166
github.com/getlantern/idletiming.(*IdleTimingConn).Read(0xc20802a910, 0xc2080aa000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /home/aranhoide/src/flashlight-build/src/github.com/getlantern/idletiming/idletiming_conn.go:106 +0x21e
net/http.(*liveSwitchReader).Read(0xc208052a48, 0xc2080aa000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc20809c840, 0xc2080aa000, 0x1000, 0x1000, 0x4134a0, 0x0, 0x0)
    /usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc208050660)
    /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc208050660, 0x40360a, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc208050660, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc208079a10, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc208079a10, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc208050660, 0xc208032d00, 0x0, 0x0)
    /usr/local/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc208052a00, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc208052a00)
    /usr/local/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 34 [runnable]:
github.com/getlantern/fronted.func·009()
    /home/aranhoide/src/flashlight-build/src/github.com/getlantern/fronted/fronted_test.go:106
created by github.com/getlantern/fronted.doTestNonGlobalAddress
    /home/aranhoide/src/flashlight-build/src/github.com/getlantern/fronted/fronted_test.go:111 +0x32d
exit status 2
FAIL    github.com/getlantern/fronted   2.216s
```

**Comment by oxtoacart** [comment]
Weird.  If you pull and try again, what do you get?

**Comment by aranhoide** [comment]
Pulling only gave me an update: a test file in fronted.  I get a different failure:

```
aranhoide@duna:~/src/flashlight-build/src/github.com/getlantern/fronted$ git pull
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 15 (delta 3), reused 0 (delta 0)
Unpacking objects: 100% (15/15), done.
From github.com:getlantern/flashlight-build
   5ea815d..a267e1a  peerscanner -> origin/peerscanner
   9cc954c..e8aa694  issue-2174 -> origin/issue-2174
Updating 5ea815d..a267e1a
Fast-forward
 src/github.com/getlantern/fronted/fronted_test.go | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)
aranhoide@duna:~/src/flashlight-build/src/github.com/getlantern/fronted$ go test
fronted: Creating new PK at: 
fronted: Creating new server cert at: 
fronted: Creating new server cert at: testcert.pem
fronted: About to start server (https) proxy at localhost:0
fronted: Not accepting connections to non-global address: 127.0.0.1:49803
enproxy: Responding Bad Gateway: Unable to get connOut: Unable to dial out to 127.0.0.1:49803: Not accepting connections to non-global address: 127.0.0.1:49803
enproxy: Failing on Dest: 127.0.0.1:49803    ProxyHost:     Unable to issue write request: Bad response status for read: 502 Bad Gateway
enproxy: Failing on Bad response status for read: 502 Bad Gateway
fronted: Creating new server cert at: testcert.pem
fronted: About to start server (https) proxy at localhost:0
--- FAIL: TestNonGlobalAddressNoPort (0.37s)
    fronted_test.go:119: Unable to dial localhost: Unable to resolve TCP addr localhost: missing port in address localhost
fronted: Creating new server cert at: testcert.pem
fronted: About to start server (https) proxy at localhost:0
fronted: Unable to resolve destination IP addr : <nil>
enproxy: Responding Bad Gateway: Unable to get connOut: Unable to dial out to :0: Unable to resolve destination IP addr : <nil>
enproxy: Failing on Dest: :0    ProxyHost:     Unable to issue write request: Bad response status for read: 502 Bad Gateway
enproxy: Failing on Bad response status for read: 502 Bad Gateway
fronted: Creating new server cert at: testcert.pem
fronted: About to start server (https) proxy at localhost:0
fronted: Not accepting connections to port 46835
enproxy: Responding Bad Gateway: Unable to get connOut: Unable to dial out to 127.0.0.1:46835: Not accepting connections to port 46835
enproxy: Failing on Dest: 127.0.0.1:46835    ProxyHost:     Unable to issue write request: Bad response status for read: 502 Bad Gateway
enproxy: Failing on Bad response status for read: 502 Bad Gateway
fronted: Creating new server cert at: testcert.pem
fronted: About to start server (https) proxy at localhost:0
fronted: Creating new server cert at: testcert.pem
fronted: About to start server (https) proxy at localhost:0
FAIL
exit status 1
FAIL    github.com/getlantern/fronted   14.495s
```

**Comment by oxtoacart** [comment]
That's actually perfect, exactly what I needed, thanks!

**Comment by aranhoide** [comment]
Np.  Should I wait for any updates related to this freeze before merging, or are you confident this issue is orthogonal to the changes in this PR?

**Comment by oxtoacart** [comment]
I'm pretty sure it's orthogonal if you want to go ahead and pull.

Cheers,
Ox

---

"I love people who harness themselves, an ox to a heavy cart,
who pull like water buffalo, with massive patience,
who strain in the mud and the muck to move things forward,
who do what has to be done, again and again."
- Marge Piercy

**Comment by oxtoacart** [comment]
@aranhoide Thanks!

**Pull request merged**
