### PR TITLE
Lantern android

### PR DESCRIPTION
**Pull request by xiam**
The [lantern-android](https://github.com/getlantern/lantern-android) project provides tools for creating a flashlight library that makes easy running and controlling a flashlight client on Android devices.

This commit provides example code and instructions.

See https://github.com/getlantern/flashlight-build/pull/36

### CODE REVIEW

**Comment by atavism** [comment]
Encountering this error again running the example application on a Nexus 5 device with Lollipop:

```
03-26 22:44:02.088      346-360/? I/ActivityManager﹕ Start proc org.getlantern.lantern for activity org.getlantern.lantern/.MainActivity: pid=1240 uid=10053 gids={50053, 9997} abi=armeabi-v7a
03-26 22:44:02.188    1240-1240/? I/art﹕ Not late-enabling -Xcheck:jni (already on)
03-26 22:44:03.307    1240-1240/? W/linker﹕ libgojni.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
03-26 22:44:03.649    1240-1255/? I/GoLog﹕ Error updating configuration over the network: "Get https://s3.amazonaws.com/lantern_config/cloud.1.6.0.yaml.gz: dial tcp: lookup s3.amazonaws.com: No address associated with hostname".
03-26 22:44:03.654    1240-1255/? I/Go﹕ app.Run
03-26 22:44:03.659    1240-1240/? I/Go﹕ runtime started
03-26 22:44:03.779    1240-1261/? A/art﹕ art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: jfieldID was NULL
```

Not sure how we resolved this before. A recent related discussion: https://github.com/golang/go/issues/9210

**Comment by atavism** [comment]
The app crashing immediately after loading the shared library was due to a [recent golang/mobile change](https://github.com/golang/mobile/commit/e3048a987d7a502a3c4031b6064c74de2a47e7ec#diff-d9c4aaa9c1242bf175222f376a9fad81) to app.Run that _requires_ [Java.Init](https://godoc.org/golang.org/x/mobile/bind/java) be passed to the Start callback.

**Comment by atavism** [comment]
Another note: if you're building your project with gradle, it'll automatically detect libgojni.so when you place it inside `src/main/jniLibs` under your app directory without any additional configuration necessary. See the discussion [here](http://stackoverflow.com/questions/17340240/jni-folder-in-android-studio). We might want to add a note about this to the README. 

Otherwise, this is working off the latest valencia branch! @myleshorton and @xiam, I think we can go ahead and merge this now.

**Comment by myleshorton** [comment]
OK I'm merging this one in too -- thanks @xiam and @atavism!

**Pull request merged**
