### PR TITLE
Revert "User settings and server-side analytics"

### PR DESCRIPTION
**Pull request by myleshorton**
Reverts getlantern/flashlight-build#138

Doesn't look right -- deleted stuff we want from valencia.

### CODE REVIEW

**Comment by atavism** [comment]
Not sure what happened. Should we merge this, and I'll create a new PR for #138 based off the latest valencia branch?

**Comment by myleshorton** [comment]
Yeah I'm reverting the merge to Valencia to just sort this out.

**Comment by myleshorton** [comment]
Yeah I think a new PR for #138 based off latest Valencia should do the trick @atavism. Tests oddly keep failing too but not on Valencia, so not sure what's up with that.

**Comment by myleshorton** [comment]
I also reverted the reverse merge from valencia to analytics (github was asking me to manually merge) after that introduced test failures, so I think we basically want to go back to 2459367b2fc36d06a8cd84f77337d7a33fbed08c and see if we can merge from there.

**Comment by atavism** [comment]
Ok here's a new PR https://github.com/getlantern/flashlight-build/pull/149

**Pull request merged**
