### PR TITLE
Autoupdate code review updates

### PR DESCRIPTION
**Pull request by oxtoacart**
Main changes:
- Switched to using semantic versioning with semver package
- Simplified autoupdate API (which also took care of a race condition or two)
- Updated example to show restart after update
- Using golog
- Slightly more informative error messages in a few places

### CODE REVIEW

**Comment by oxtoacart** [comment]
@xiam - Here are some suggested changes.

**Comment by fffw** [comment]
@oxtoacart Those additional files under `flashlight` and `lantern-ui` are unintentionally included?

**Comment by oxtoacart** [comment]
@fffw 

> Those additional files under flashlight and lantern-ui are unintentionally included?

Oops.  Removed.

**Comment by xiam** [comment]
@oxtoacart Thank you Ox, looking into it.

**Comment by xiam** [comment]
Cools suggestions Ox!

**Comment by oxtoacart** [comment]
Glad you liked them, thanks for reviewing!

**Pull request merged**
