### PR TITLE
Better logging for geolookup errors

### PR DESCRIPTION
**Pull request by oxtoacart**
This doesn't fix getlantern/lantern#2285, but it should help diagnose them.

### CODE REVIEW

**Comment by xiam** [comment]
Hey @oxtoacart, I noticed that we're targeting the valencia branch, should we continue using it as our development target?

**Comment by oxtoacart** [comment]
@xiam Yes.  I've made valencia the default branch now.  We'll keep devel for supporting the old flashlight used by the Java Lantern version.

**Comment by xiam** [comment]
Got it @oxtoacart, looks good to me!

**Comment by oxtoacart** [comment]
@xiam Thanks for reviewing!

**Pull request merged**
