### PR TITLE
Pull changes to support building OS X App Bundle and DMG

### PR DESCRIPTION
**Pull request by oxtoacart**
@xiam Do you mind taking a look at this since it's related to the auto update stuff you've been working on?

### CODE REVIEW

**Comment by xiam** [comment]
@oxtoacart Sure Ox, my pleasure.

**Comment by xiam** [comment]
Looks great @oxtoacart, the travis test fails because some error with `pkg-config` originated in `./src/github.com/getlantern/systray/systray_nonwindows.go`, but this PR didn't touch that part. We can take care of the failing test later.

**Comment by oxtoacart** [comment]
Thanks @xiam.  Yeah, those tests are failing in all of the Valencia branches since we introduced systray.  I'm actually working on fixing them right now.

**Comment by oxtoacart** [comment]
BTW, those tests are fixed now.

**Pull request merged**
