### PR TITLE
getlantern/lantern#2210 Peerscanner now maintains country-specific fallb...

### PR DESCRIPTION
**Pull request by oxtoacart**
...ack rotations

### CODE REVIEW

**Comment by oxtoacart** [comment]
I went ahead and made the change to use nl.fallbacks.getiantem.org and made peers 2% of the rotation.

**Comment by oxtoacart** [comment]
@atavism Ping.

**Comment by atavism** [comment]
@oxtoacart I was still testing this. I'm seeing two of the servers I deployed earlier in the Netherlands fallback group. I'm going to assume flashlight hasn't started on the third yet. Did you push the updated cloud.yaml yet? Changes look fine though. I'll merge.

**Comment by oxtoacart** [comment]
@atavism Thanks!

What url are we using the cloud.yaml for the valencia release?

**Comment by atavism** [comment]
http://s3.amazonaws.com/lantern_config/cloud.valencia.yaml.gz

**Comment by oxtoacart** [comment]
Cool, I've regenerated config and uploaded.

**Pull request merged**
