### PR TITLE
Ubuntu installer

### PR DESCRIPTION
**Pull request by aranhoide**
This builds ubuntu 64-bit installers.  Presumably, 32-bit installers would be built if this is run in a 32-bit machine, but I haven't tested that yet.  I'll try and build these in docker images.

### CODE REVIEW

**Comment by oxtoacart** [comment]
Very cool! It works for me right out of the box.

Here is what pops out at me that could be improved:
- The README could use an update to cover the new script.
- Ubuntu's package manager complains if we build with a version number that doesn't match the Deb requirements.  Might want to mention that in the README and link here - https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version
- I ran lintian on the package and there are some errors and warnings.  Some we can't fix, in particular we can't strip the binary (Go binaries don't like to be stripped), and the embedded libraries are a result of us statically linking (which we probably don't want to mess with right now).  The errors and some of the warnings are probably things we could fix though.

``` bash
ox@ubuntu:~/flbuild$ lintian lantern_2.0.0-beta1_amd64.deb 
E: lantern: unstripped-binary-or-object usr/bin/lantern
E: lantern: embedded-library usr/bin/lantern: libyaml
E: lantern: embedded-library usr/bin/lantern: libminiupnpc
W: lantern: hardening-no-relro usr/bin/lantern
W: lantern: missing-depends-line
E: lantern: no-copyright-file
E: lantern: extended-description-is-empty
W: lantern: unknown-section default
W: lantern: non-standard-dir-perm usr/ 0775 != 0755
W: lantern: non-standard-dir-perm usr/bin/ 0775 != 0755
W: lantern: non-standard-dir-perm usr/share/ 0775 != 0755
W: lantern: non-standard-dir-perm usr/share/applications/ 0775 != 0755
W: lantern: non-standard-executable-perm usr/share/applications/lantern.desktop 0775 != 0755
W: lantern: non-standard-dir-perm usr/share/doc/ 0775 != 0755
W: lantern: non-standard-dir-perm usr/share/doc/lantern/ 0775 != 0755
W: lantern: non-standard-dir-perm usr/share/icons/ 0775 != 0755
W: lantern: non-standard-dir-perm usr/share/icons/hicolor/ 0775 != 0755
W: lantern: non-standard-dir-perm usr/share/icons/hicolor/128x128/ 0775 != 0755
W: lantern: non-standard-dir-perm usr/share/icons/hicolor/128x128/apps/ 0775 != 0755
W: lantern: non-standard-file-perm usr/share/icons/hicolor/128x128/apps/lantern.png 0664 != 0644
W: lantern: binary-without-manpage usr/bin/lantern
W: lantern: file-missing-in-md5sums usr/share/doc/lantern/changelog.Debian.gz
E: lantern: executable-desktop-file usr/share/applications/lantern.desktop 0775
W: lantern: unusual-interpreter usr/share/applications/lantern.desktop #!xdg-open
```

**Comment by aranhoide** [comment]
I'll update the README.  I'll mention the version name thing too.  Incidentally, aren't our version names compatible with Deb requirements?  I didn't get any such complaints while testing.

I'll look into what warnings and errors it makes sense to fix.  So far, I just fixed the errors that caused the Ubuntu package manager to complain that our package is of bad quality.

**Comment by aranhoide** [comment]
I updated the README, changed the compression to xz, which brings the size down to 3MB, and fixed a few of the lintian complaints.  This is what lintian says now:

```
E: lantern: unstripped-binary-or-object usr/bin/lantern
E: lantern: embedded-library usr/bin/lantern: libyaml
E: lantern: embedded-library usr/bin/lantern: libminiupnpc
W: lantern: hardening-no-relro usr/bin/lantern
W: lantern: missing-depends-line
W: lantern: wrong-name-for-changelog-of-native-package usr/share/doc/lantern/changelog.Debian.gz
W: lantern: extended-description-line-too-long
W: lantern: binary-without-manpage usr/bin/lantern
W: lantern: file-missing-in-md5sums usr/share/doc/lantern/changelog.Debian.gz
```

Re: this `hardening-no-relro` flag, see:

https://lintian.debian.org/tags/hardening-no-relro.html

I'm not sure we can fix this in Go.

Note that the changelog is auto-generated by fpm, so it is useless anyway.  I think the warnings related to it don't matter unless we fix all others and want to submit this to some official repo.

I think we can safely ignore the "missing depends" warning since we pack our own dependencies.  The extended-description-line-too-long is a matter of taste, I guess.  The extended description displays just fine in the Ubuntu Software Center and in the Synaptic properties window.

**Comment by oxtoacart** [comment]
Awesome!  I tested on a 32bit ubuntu and it worked.  I've updated the README accordingly and will now merge.  Nice work!  Gotta say, I love the simplicity of this.

**Comment by aranhoide** [comment]
Thanks!  The main challenge here was realising just how simple this could be.  `fpm` really made this a breeze.  I wish I'd tinkered with that when you first mentioned it.  I kind of assumed that even in order to use fpm I'd need to get acquainted with the OS X and Windows distributions, and debian packaging.  I guess I can at least partially blame this on install4j PTS. :P

**Pull request merged**
