### PR TITLE
avoid breaking out of register loop on PostForm error

### PR DESCRIPTION
**Pull request by aranhoide**

### CODE REVIEW

**Comment by myleshorton** [comment]
Nice! Yeah we seem to have quite a lot of servers out of rotation, so would be awesome to deploy this.

**Comment by aranhoide** [comment]
OK, will do.  But first I suppose I should backport this to `devel`, since we were doing releases from there (right, @oxtoacart ?).  Just in case it takes a while for you to read this, I'll just restart the flashlight service on these machines, which should get them back into rotation.

**Comment by myleshorton** [comment]
Oh good point @aranhoide. Are you talking about restarting flashlight on all the machines or just the ones from the syslog? Keep in mind that was just the syslog from _today_ -- the syslogs for prior days are similar. So we're killing something like 20 of these/day.

**Comment by aranhoide** [comment]
Oh wow.

I did restart them all.  A ~dozen of the flashlight servers are not responding to the cloudmaster, I guess because they're overloaded.  I'll look into them.

**Comment by aranhoide** [comment]
Those twelve seem to be hopelessly overloaded.  Connecting to them via ssh times out.  Although those were in Singapore, I'll just kill them and launch new ones in the Netherlands, which IIRC worked better than Singapore for China anyway.

**Comment by myleshorton** [comment]
Awesome thanks!

On Tuesday, March 17, 2015, aranhoide notifications@github.com wrote:

> Those twelve seem to be hopelessly overloaded. Connecting to them via ssh
> times out. Although those were in Singapore, I'll just kill them and launch
> new ones in the Netherlands, which IIRC worked better than Singapore for
> China anyway.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/getlantern/flashlight-build/pull/130#issuecomment-82643634
> .

## 

## 

President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Pull request merged**
