### PR TITLE
only link .syso on 386 arch to resolve lantern#2384

### PR DESCRIPTION
**Pull request by fffw**
Resolves https://github.com/getlantern/lantern/issues/2384

### CODE REVIEW

**Comment by fffw** [comment]
@aranhoide Would you like to take a look?

**Comment by xiam** [comment]
Cool @fffw, would not this affect Linux 386 too?

Maybe I can fix this on the Makefile side for that case, what do you think?

**Comment by fffw** [comment]
@xiam I don't have Linux 386 VM installed, may worth for a test. Maybe `lantern_win_386.syso` works?

**Comment by xiam** [comment]
@fffw Don't worry, I have a couple of machines ready for testing, I'll try and see.

**Comment by xiam** [comment]
I'll take this one, if you don't mind @aranhoide.

**Comment by xiam** [comment]
The windows_386 thing worked @fffw, great tip! Thanks.

**Pull request merged**
