### PR TITLE
Welcome Screen

### PR DESCRIPTION
**Pull request by atavism**

### CODE REVIEW

**Comment by oxtoacart** [comment]
Concept is cool and implementation works for me on Chrome, Firefox and Safari on OS X.  I only have two questions:
1. Have the translation strings been submitted to Transifex and do we think we'll have them (especially the persian translation) in time to release?
2. The typography looks different than our usual style.  Has this received the Carson and Derek treatment already?

**Comment by atavism** [comment]
> Have the translation strings been submitted to Transifex and do we think we'll have them (especially the persian translation) in time to release?

Yes. I'll shoot Derek an e-mail to reach out to the Persian translators.

> The typography looks different than our usual style. Has this received the Carson and Derek treatment already?

Yeah, looks like we weren't using the right font family. I just fixed that. Carson came up with the design.

**Comment by myleshorton** [comment]
Yeah we could surely get Katayoun, Chip, and Merlin to do some quick
translations.

On Sun, Feb 22, 2015 at 5:47 AM, Coveralls <notifications@github.com> wrote:

> [image: Coverage Status] <https://coveralls.io/builds/1973592>
>
> Coverage decreased (-0.61%) to 66.73% when pulling *9d81166
> <https://github.com/getlantern/flashlight-build/commit/9d8116631d4f457b0b156a10ebe3319ecd8ac395>
> on welcome* into *ac5cc4f
> <https://github.com/getlantern/flashlight-build/commit/ac5cc4fe468fb02c7ebae87f752b226e56159b05>
> on valencia*.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/flashlight-build/pull/78#issuecomment-75441334>
> .
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by myleshorton** [comment]
I also noticed it makes the Twitter and Facebook requests regardless of whether or not we show the screen. Can we load it dynamically to avoid that? Not a huge deal, but would make the UI load a little quicker.

**Comment by atavism** [comment]
> I also noticed it makes the Twitter and Facebook requests regardless of whether or not we show the screen. Can we load it dynamically to avoid that? Not a huge deal, but would make the UI load a little quicker.

Sure, I'll make that change.

**Comment by atavism** [comment]
@myleshorton The FB and Twitter scripts are being loaded dynamically now (the first time the "Welcome" screen is shown/open).

**Comment by myleshorton** [comment]
Nice!

On Monday, February 23, 2015, Coveralls notifications@github.com wrote:

> [image: Coverage Status] https://coveralls.io/builds/1979486
> 
> Coverage increased (+1.56%) to 66.36% when pulling _03a770e
> https://github.com/getlantern/flashlight-build/commit/03a770e27eeafe0e2cfea7ef808efe25f664722a
> on welcome_ into _3ebe2c1
> https://github.com/getlantern/flashlight-build/commit/3ebe2c17e7f3a07e3baa582ad15f37dea87578ef
> on valencia_.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/getlantern/flashlight-build/pull/78#issuecomment-75584369
> .

## 

## 

President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by oxtoacart** [comment]
LGTM.

**Comment by atavism** [comment]
@oxtoacart Great! Thanks for reviewing!

**Pull request merged**
